TESTING: false
SMALL_TRAINING: false
GPU: true
TEST_FREQ: 1
plot_freq: 50
images_to_load: null
load_path: false
test_only: false
experiment: CRCR
name: baseline
output_folder: ./results
epochs_to_run: 200
save_freq: 1
use_visdom: true
debug: false
decoder_type: naive
optimizer_type: adam
validation_jsons:
- prepare_IAM_Lines/gts/lines/txt/val1.json
- prepare_IAM_Lines/gts/lines/txt/val2.json
training_jsons:
- munit/online_munit_v1.json
training_root: data
training_shuffle: false
training_warp: true
online_augmentation: true
online_flag: false
writer_id_pickles:
- prepare_IAM_Lines/writer_IDs.pickle
- prepare_online_data/writer_IDs.pickle
testing_jsons:
- prepare_IAM_Lines/gts/lines/txt/test.json
testing_root: ../simple_hwr/data
testing_shuffle: false
n_warp_iterations: 0
testing_warp: false
testing_occlude: false
output_predictions: false
style_encoder: false
batch_size: 16
input_height: 60
cnn_out_size: 1024
num_of_channels: 1
rnn_dimension: 512
rnn_layers: 2
rnn_type: lstm
cnn: default
recognizer_dropout: 0.5
writer_dropout: 0.4
writer_rnn_dimension: 128
writer_rnn_output_size: 256
mlp_layers:
- 64
- embedding
- 64
embedding_size: 32
learning_rate: 0.0002
scheduler_step: 10
scheduler_gamma: 0.95
occlusion_size: null
occlusion_freq: null
occlusion_level: null
training_random_distortions: false
training_blur: false
